TestComplexInsert passes
Whoop!

1. Add back in the 10 total inserts so the checks based on these pass
2. Need the `parseTime=true` otherwise get:

		writer_test.go:182: Error on test query: sql: Scan error on column index 2, name "coltimestamp": unsupported Scan, storing driver.Value type []uint8 into type *time.Time