Very initial work on MySQL, copying Postgresql
- Copy files, don't bother with tests except client for now
- Change names from Postgresq, pq, etc to MySQL, etc
- Use github.com/go-sql-driver/mysql
- Don't bother with tailing for now
- Move the `casifyValue` function from tailing.go to reader.go since it seems it's needed even without tailing.

It "builds", but the tests fail with the below currently:

```
$ go117 test
--- FAIL: TestConnect (0.03s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x11078d3]

goroutine 7 [running]:
testing.tRunner.func1.2({0x123b0a0, 0x143e550})
        /opt/pkg/go117/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
        /opt/pkg/go117/src/testing/testing.go:1212 +0x218
panic({0x123b0a0, 0x143e550})
        /opt/pkg/go117/src/runtime/panic.go:1038 +0x215
database/sql.(*DB).conn(0x0, {0x12ca330, 0xc00001e098}, 0x1)
        /opt/pkg/go117/src/database/sql/sql.go:1260 +0x53
database/sql.(*DB).PingContext(0x1278b3b, {0x12ca330, 0xc00001e098})
        /opt/pkg/go117/src/database/sql/sql.go:853 +0x7a
database/sql.(*DB).Ping(...)
        /opt/pkg/go117/src/database/sql/sql.go:874
github.com/compose/transporter/adaptor/mysql.(*Client).Connect(0x143f8e0)
        /Users/simon/Code/go/src/github.com/compose/transporter/adaptor/mysql/client.go:76 +0xdc
github.com/compose/transporter/adaptor/mysql.TestConnect(0xc000111380)
        /Users/simon/Code/go/src/github.com/compose/transporter/adaptor/mysql/client_test.go:76 +0xfe
testing.tRunner(0xc000111380, 0x1285c58)
        /opt/pkg/go117/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
        /opt/pkg/go117/src/testing/testing.go:1306 +0x35a
exit status 2
FAIL    github.com/compose/transporter/adaptor/mysql    0.832s
```

However... that is to be expected. I haven't altered anything else to be MySQL specific and don't have a local instance of MySQL running.