Add writer tests. Run, but fail.
Copied from Postgresql and making the obvious changes (ugh... I really
should have done commits before changing anything... oh well):

- Changing the NewClient urls
- Changing pqSession to mysqlSession
- Changing from "public.table" to "database.table"

Still lots here that is Postgresql specific though.

Working on just one writer test at a time so have uncommented
writerTestData in adaptor_test for now.

This is where things are at the moment:

```
INFO[0000] no function registered for operation, command
INFO[0000] no function registered for operation, command
--- FAIL: TestInsert (0.11s)
    writer_test.go:62: unexpected Insert error, Error 1054: Unknown column '$1' in 'field list'
[...]
    writer_test.go:93: Error on test query: sql: no rows in result set
```